name: ci

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main
      - 'release/**'

jobs:
  go-lint:
    name: go-lint
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.23.4'
          cache: true

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run golangci-lint
        run: golangci-lint run ./...
  
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.23.4'
          cache: true
      
      - name: Install dependencies
        run: go mod download
      
      - name: Build
        run: go build -v ./cmd/...
      
      - name: Run tests
        run: go test -v ./...
  
  # python-lint:
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: astral-sh/ruff-action@v3
  #       with:
  #         args: check
  #         src: './tools'
