name: release

on:
  push:
    tags:
    - '*'

jobs:
  build-and-publish-archive:
    permissions:
      contents: write

    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.23.4'
          cache: true
      
      - name: Create distribution directory
        run: mkdir server
      
      - name: Install dependencies
        run: go mod download

      - name: Build server
        run: go build -v ../cmd/uv_server
        working-directory: server
      
      - name: Build launcher
        run: go build -v ../cmd/launcher
        working-directory: server
      
      - name: Prepare ffmpeg
        run: |
          Invoke-WebRequest -Uri https://github.com/yt-dlp/FFmpeg-Builds/releases/download/latest/ffmpeg-n7.1-latest-win64-gpl-7.1.zip -OutFile ffmpeg.zip
          Expand-Archive -Path .\ffmpeg.zip -DestinationPath ./ffmpeg
          mv ffmpeg/ffmpeg-n7.1-latest-win64-gpl-7.1 .
          rm ffmpeg.zip
          rm ffmpeg
        working-directory: server
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Create tools directory
        run: mkdir server/tools

      - name: Build downloader
        run: |
          python -m venv venv 
          .\venv\Scripts\Activate.ps1; pip install -r requirements.txt
          .\venv\Scripts\Activate.ps1; pyinstaller --onefile .\downloader.py
        working-directory: tools/downloaders/youtube
      
      - name: Add downloader to distribution
        run: |
          cp ./tools/downloaders/youtube/dist/downloader.exe ./server/tools
      
      - name: Copy migrations
        run:
          mv ./db ./server
      
      - name: Copy config
        run: |
          mkdir ./server/config
          cp ./configs/config.yaml ./server/config

      - name: Package distribution directory
        run: |
          Compress-Archive -LiteralPath .\server -DestinationPath server.zip
      
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts:
            "server.zip,launcher.exe"
